add Metric Unit of measure (UOM) to Nagios output
paulgear/ntpmon pull request #4
Opened 2019-08-13 01:36 UTC by fbourqui

The Metric UOM will be dispayed in RRD graph.

2019-08-14 23:01 UTC, fbourqui commented
Hello second commit is to avoid python crash when running check_ntpmon and no NTP process is found, it will return the readable message, and the return code -1 (255), I id not found an elegant way to return(2) :

CRITICAL: No NTP process could be found.  Please check that an NTP server is installed and running.

2020-10-05 08:37 UTC, paulgear commented
Hi @fbourqui,

Thanks for the PR - I'm not sure why I didn't see it until just recently.  I'll check my notification settings, but I want to get these changes merged.  I've got a couple of minor comments on the code which I'll add shortly, but if you're not in a position to make changes, then I'll just merge and commit a tidy-up afterwards.

One question: what Nagios setup are you using which makes use of the units of measure, and is there an easy way you can test any updates non-invasively?  I'm spinning up a test Nagios server in a Docker container at the moment, so I should be able to do some basic sanity checking, but I'd like to make sure that your requirements are met by the changes.

Regards,
Paul

2020-10-05 09:53 UTC, paulgear requested changes
@fbourqui After your comment about finding an elegant way of producing the correct output, I had another look at the existing master, and I've got a change prepared which is much shorter and hopefully clearer.  I think we'd be best to roll back your PR to being just the Units of Measure change, and I'll put my proposed change up in a separate branch for your testing & feedback.

2020-10-05 09:53 UTC, paulgear commented on src/alert.py
> +    'frequency': 'ms',
My understanding of frequency is that it's not in milliseconds, but parts-per-million.  I'm not sure if that is something that is easily representable by Nagios' available units of measure; if not, I think microseconds would be more accurate than milliseconds.

2020-10-05 09:53 UTC, paulgear commented on src/alert.py
> +                self.checks.append('sysoffset')
It looks like most of this change is just an indent.  If that's the case, I'd prefer to see just:

    if not checkobjs:
        return
    ... # the rest of the function unchanged

2020-10-05 09:53 UTC, paulgear commented on src/alert.py
> +
Like you say, I think we need to find an elegant method to do this without duplicating the error messages which are already produced under other circumstances.

2020-10-05 09:53 UTC, paulgear commented on src/alert.py
> +                print('%s | %s' % (msgs[m], self.report()))
Same comment as above applies here.

2020-10-05 17:43 UTC, fbourqui commented
Hello Paul,





I'm using your nagios plugin with librenms (yes it has support for nagios plugin).



I'm quite busy right now with other topics, but I will take some time to check if your changes are working for my librenms use case, I will let you know when I have time to validate that, most probably next week.



Cheers,

Fred





---- On Mon, 05 Oct 2020 10:37:28 +0200 Paul Gear <notifications@github.com> wrote ----





Hi https://github.com/fbourqui,

Thanks for the PR - I'm not sure why I didn't see it until just recently.  I'll check my notification settings, but I want to get these changes merged.  I've got a couple of minor comments on the code which I'll add shortly, but if you're not in a position to make changes, then I'll just merge and commit a tidy-up afterwards.

One question: what Nagios setup are you using which makes use of the units of measure, and is there an easy way you can test any updates non-invasively?  I'm spinning up a test Nagios server in a Docker container at the moment, so I should be able to do some basic sanity checking, but I'd like to make sure that your requirements are met by the changes.

Regards,
 Paul
—
You are receiving this because you were mentioned.
Reply to this email directly, https://github.com/paulgear/ntpmon/pull/4#issuecomment-703488778, or https://github.com/notifications/unsubscribe-auth/AAYGV62FRPZRPPZ3NTUDUOTSJGAURANCNFSM4ILGJTJQ.

2023-12-22 05:22 UTC, paulgear commented
Hi @fbourqui, the main branch has moved along a bit since this PR and I've merged the change which correctly detects the non-running NTP service.  If you have any further changes to propose around the units of measure issue, please drop me a new PR forked from the current main branch.

2023-12-22 05:22 UTC, closed without merging